### ISSUE TITLE
Top NeoVim Plugins of 2020 - breuer.dev

### ISSUE THREAD

**Issue by breuerfelix** [breuerfelix/breuerfelix.github.io#19]
https://breuer.dev/blog/top-neovim-plugins.html 

 I recently tried to find some new interesting NeoVim plugins and realised that there are not many people blogging about their setup in 2019/2020.There are ma...

**Comment by OneManDevz** [comment]
Like and subscribe. 
```javascript
let me = "see if the markdown is working"
```

**Comment by breuerfelix** [comment]
> @OneManDevz
> Like and subscribe. 
> ```javascript
> let me = "see if the markdown is working"
> ```

thanks mate! i also wanna test out if replies are working
