### ISSUE TITLE
Setup NextCloud Server with Nginx SSL Reverse-Proxy and Apache2 Backend - breuer.dev

### ISSUE THREAD

**Issue by breuerfelix** [breuerfelix/breuerfelix.github.io#20]
https://breuer.dev/tutorial/Setup-NextCloud-FrontEnd-Nginx-SSL-Backend-Apache2.html 

 In the next few chapters we gonna setup a NextCloud Server from scratch.There are alot of tutorials out there already covering this topic, but in our case we...

**Comment by xalgia** [comment]
This is *the best* nextcloud reverse proxy guide out there, thank you!
